[package]
name = "trie-eip1186"
version = "0.5.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "EIP-1186 compliant proof generation and verification"
repository = "https://github.com/paritytech/trie"
license = "Apache-2.0"
edition = "2018"

[dependencies]
trie-db-fun = { path = "../trie-db", default-features = false, version = "100.28.0"}
hash-db = { path = "../hash-db", default-features = false, version = "0.16.0"}

[features]
default = ["std"]
std = [
  "trie-db-fun/std",
  "hash-db/std",
]
